version: "3.5"

services:
  mysql:
    container_name: wallet_mysql
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet-user
      MYSQL_PASSWORD: wallet-password
    networks:
      - wallet_default

  wallet_service:
    container_name: wallet_service
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

networks:
  wallet_default:

volumes:
  database:
